### ISSUE TITLE
Repository port

### ISSUE THREAD

**Issue by olenagerasimova** [artipie/artipie#1041]
There are two problems when repository port is specified. Let's say artipie main port is 8085 and repository `den` port is 8088, then

1) repository is available on artipie main port, that is on http://localhost:8085/den. This is not correct, NOT FOUND error should be returned in thos case

2) when repository port is specified, repository is not accessible on http://localhost:8088/den, but it's accessible without repo name by http://localhost:8088/. That is not correct either, repository should be accessible on http://localhost:8088/den

**Comment by 0pdd** [comment]
@olenagerasimova 10 puzzles [#1044](https://github.com/artipie/artipie/issues/1044), [#1045](https://github.com/artipie/artipie/issues/1045), [#1046](https://github.com/artipie/artipie/issues/1046), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1049](https://github.com/artipie/artipie/issues/1049), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1050](https://github.com/artipie/artipie/issues/1050).

**Comment by 0pdd** [comment]
@olenagerasimova 8 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1046](https://github.com/artipie/artipie/issues/1046), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1049](https://github.com/artipie/artipie/issues/1049), [#1051](https://github.com/artipie/artipie/issues/1051), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1050](https://github.com/artipie/artipie/issues/1050), [#1052](https://github.com/artipie/artipie/issues/1052).

**Comment by 0pdd** [comment]
@olenagerasimova 7 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1046](https://github.com/artipie/artipie/issues/1046), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1049](https://github.com/artipie/artipie/issues/1049), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1050](https://github.com/artipie/artipie/issues/1050), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052).

**Comment by 0pdd** [comment]
@olenagerasimova 6 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1049](https://github.com/artipie/artipie/issues/1049), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1046](https://github.com/artipie/artipie/issues/1046), [#1050](https://github.com/artipie/artipie/issues/1050), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052).

**Comment by 0pdd** [comment]
@olenagerasimova 5 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1049](https://github.com/artipie/artipie/issues/1049), [#1055](https://github.com/artipie/artipie/issues/1055) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1046](https://github.com/artipie/artipie/issues/1046), [#1050](https://github.com/artipie/artipie/issues/1050), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052), [#1054](https://github.com/artipie/artipie/issues/1054).

**Comment by 0pdd** [comment]
@olenagerasimova 4 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1049](https://github.com/artipie/artipie/issues/1049) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1046](https://github.com/artipie/artipie/issues/1046), [#1050](https://github.com/artipie/artipie/issues/1050), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055).

**Comment by 0pdd** [comment]
@olenagerasimova 3 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1047](https://github.com/artipie/artipie/issues/1047), [#1049](https://github.com/artipie/artipie/issues/1049) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1046](https://github.com/artipie/artipie/issues/1046), [#1048](https://github.com/artipie/artipie/issues/1048), [#1050](https://github.com/artipie/artipie/issues/1050), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055).

**Comment by olenagerasimova** [comment]
done with puzzles

**Comment by 0pdd** [comment]
@olenagerasimova 2 puzzles [#1045](https://github.com/artipie/artipie/issues/1045), [#1049](https://github.com/artipie/artipie/issues/1049) are still not solved; solved: [#1043](https://github.com/artipie/artipie/issues/1043), [#1044](https://github.com/artipie/artipie/issues/1044), [#1046](https://github.com/artipie/artipie/issues/1046), [#1047](https://github.com/artipie/artipie/issues/1047), [#1048](https://github.com/artipie/artipie/issues/1048), [#1050](https://github.com/artipie/artipie/issues/1050), [#1051](https://github.com/artipie/artipie/issues/1051), [#1052](https://github.com/artipie/artipie/issues/1052), [#1054](https://github.com/artipie/artipie/issues/1054), [#1055](https://github.com/artipie/artipie/issues/1055).

**Comment by 0pdd** [comment]
@olenagerasimova the puzzle [#unknown]() is still not solved.

**Comment by 0pdd** [comment]
@olenagerasimova the only puzzle [#unknown]() is solved here.
