### ISSUE TITLE
Artipie MVP

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#12]
Create simple Artipie server. It should:
 - read configuration files and include adapters from these files
 - delegate HTTP requests to enabled adapters
 - implements `Front` interface from artipie/http module

**Comment by g4s8** [comment]
@0crat assign me

**Comment by Sammers21** [comment]
@g4s8, I would say the artipie server should:
* read an `artipie.yml` file
* read repository configuration files from asto

**Comment by Sammers21** [comment]
> implements Front interface from artipie/http module

What is meant by this?

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/artipie/artipie/issues/12#issuecomment-582003146))

@g4s8 The job [#12](https://github.com/artipie/artipie/issues/12) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e3fd1cef-cc72-4351-a4ab-0bf3e80aa625); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
It is strongly discouraged to assign jobs to their creators, see [§19](http://www.zerocracy.com/policy.html#19): -15 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @g4s8[/z](https://www.0crat.com/u/g4s8)

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#26](https://github.com/artipie/artipie/issues/26), [#27](https://github.com/artipie/artipie/issues/27) are still not solved.

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#27](https://github.com/artipie/artipie/issues/27) is still not solved; solved: [#26](https://github.com/artipie/artipie/issues/26).

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#27](https://github.com/artipie/artipie/issues/27), [#32](https://github.com/artipie/artipie/issues/32) are still not solved; solved: [#26](https://github.com/artipie/artipie/issues/26).

**Comment by g4s8** [comment]
Done

**Comment by 0crat** [comment]
Job `gh:artipie/artipie#12` is not assigned, can't get performer

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#27](https://github.com/artipie/artipie/issues/27) is still not solved; solved: [#26](https://github.com/artipie/artipie/issues/26), [#32](https://github.com/artipie/artipie/issues/32).

**Comment by 0pdd** [comment]
@g4s8 all 3 puzzles are solved here: [#26](https://github.com/artipie/artipie/issues/26), [#27](https://github.com/artipie/artipie/issues/27), [#32](https://github.com/artipie/artipie/issues/32).
