### ISSUE TITLE
debian repository - error uploading my deb artifact to S3

### ISSUE THREAD

**Issue by Tzahif** [artipie/artipie#1367]
Hi,
I am trying to upload my deb artifact to S3 and I am getting errors.
Repos configs:

my-deb-s3.yaml
````
repo:
  type: deb
  storage:
    type: s3
    bucket: repo-test
    region: us-east-1
  settings:
    Components: main
    Architectures: amd64 arm64
````

Upload to S3 command and response:
````
➜  debian curl -i  -X PUT  --data-binary "@my-package.deb" http://0.0.0.0:8888/my-deb-s3/main/my-package.deb

HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
content-length: 5935

java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
        at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
        at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at com.artipie.asto.s3.S3Storage.lambda$exists$0(S3Storage.java:122)
        at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:54)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:67)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:167)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.artipie.asto.ArtipieIOException: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
        at com.artipie.asto.s3.S3Storage.lambda$delete$9(S3Storage.java:250)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
        ... 46 more
Caused by: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
        at com.artipie.asto.ArtipieIOException.<init>(ArtipieIOException.java:59)
        ... 48 more
````
Upload to S3 artipie logs:
````
[INFO] 2024-01-09 11:58:39,898 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - >> PUT /my-deb-s3/main/my-package.deb HTTP_1_1

Host: 0.0.0.0:8888
User-Agent: curl/8.1.2
Accept: */*
Content-Length: 41386400
Content-Type: application/x-www-form-urlencoded
Expect: 100-continue
[INFO] 2024-01-09 11:58:40,080 ForkJoinPool.commonPool-worker-8 com.artipie.http.MainSlice - << CONTINUE
Jan 09, 2024 11:58:40 AM com.artipie.asto.LoggingStorage log
INFO: Exists 'my-deb-s3/dists/my-deb-s3/Release': false
Jan 09, 2024 11:58:40 AM com.artipie.asto.LoggingStorage log
INFO: List 'my-deb-s3': 0
Jan 09, 2024 11:58:40 AM com.artipie.asto.LoggingStorage log
INFO: Save 'my-deb-s3/dists/my-deb-s3/Release': Optional[119]
Jan 09, 2024 11:58:40 AM com.artipie.asto.LoggingStorage log
INFO: Exists 'my-deb-s3/dists/my-deb-s3/Release.gpg': false
Jan 09, 2024 11:58:40 AM com.artipie.asto.LoggingStorage log
INFO: Value 'my-deb-s3/dists/my-deb-s3/Release': Optional[119]
[WARN] 2024-01-09 11:58:40,526 aws-java-sdk-NettyEventLoop-1-2 software.amazon.awssdk.http.nio.netty.internal.ResponseHandler - [Channel: f3fe81e9] Subscriber cancelled before all events were published
Jan 09, 2024 11:58:40 AM com.artipie.asto.LoggingStorage log
INFO: Save 'my-deb-s3/dists/my-deb-s3/InRelease': Optional[119]
[INFO] 2024-01-09 11:58:49,892 sdk-async-response-0-7 com.artipie.http.MainSlice - Failure: java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
	at java.base/java.util.concurrent.CompletableFuture.encodeRelay(CompletableFuture.java:368)
	at java.base/java.util.concurrent.CompletableFuture.completeRelay(CompletableFuture.java:377)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1152)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at com.artipie.asto.s3.S3Storage.lambda$exists$0(S3Storage.java:122)
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallMetricCollectionStage.lambda$execute$0(AsyncApiCallMetricCollectionStage.java:54)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncApiCallTimeoutTrackingStage.lambda$execute$2(AsyncApiCallTimeoutTrackingStage.java:67)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.utils.CompletableFutureUtils.lambda$forwardExceptionTo$0(CompletableFutureUtils.java:76)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2194)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeAttemptExecute(AsyncRetryableStage.java:103)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.maybeRetryExecute(AsyncRetryableStage.java:181)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryingExecutor.lambda$attemptExecute$1(AsyncRetryableStage.java:167)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$null$0(MakeAsyncHttpRequestStage.java:105)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2179)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage.lambda$executeHttpRequest$3(MakeAsyncHttpRequestStage.java:163)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: com.artipie.asto.ArtipieIOException: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
	at com.artipie.asto.s3.S3Storage.lambda$delete$9(S3Storage.java:250)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	... 46 more
Caused by: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb
	at com.artipie.asto.ArtipieIOException.<init>(ArtipieIOException.java:59)
	... 48 more
````

**Comment by ChGen** [comment]
Could be related to https://github.com/artipie/artipie/issues/1343

**Comment by Tzahif** [comment]
@ChGen i see #1343 is closed, and it did not solve this issue

**Comment by olenagerasimova** [comment]
@Tzahif do not specify deb package name in the request line. Request example can be found [here ](https://github.com/artipie/artipie/wiki/debian) (at the bottom of the page)

**Comment by Tzahif** [comment]
@olenagerasimova i removed the package name. sorry for the mistake

**Comment by ChGen** [comment]
Fixed in origin/master.

**Comment by Tzahif** [comment]
@ChGen, i am still getting the same error when i am working with real S3 bucket:` java.util.concurrent.CompletionException: com.artipie.asto.ArtipieIOException: java.io.IOException: Key does not exist: my-deb-s3/main/my-package.deb`

when i am using minio i am getting another error:
```artipie  | [INFO] 2024-02-11 16:38:17,833 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - >> PUT /my-deb-s3/main/my-package.deb HTTP_1_1
artipie  |
artipie  | Host: 0.0.0.0:8080
artipie  | User-Agent: curl/8.1.2
artipie  | Accept: */*
artipie  | Content-Length: 41447968
artipie  | Content-Type: application/x-www-form-urlencoded
artipie  | Expect: 100-continue
artipie  | [INFO] 2024-02-11 16:38:17,840 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - << CONTINUE
artipie  | Feb 11, 2024 4:38:17 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Exists 'my-deb-s3/dists/my-deb-s3/Release': false
artipie  | Feb 11, 2024 4:38:17 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: List 'my-deb-s3': 0
artipie  | Feb 11, 2024 4:38:17 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Save 'my-deb-s3/dists/my-deb-s3/Release': Optional[110]
artipie  | Feb 11, 2024 4:38:17 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Exists 'my-deb-s3/dists/my-deb-s3/Release.gpg': false
artipie  | Feb 11, 2024 4:38:17 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Value 'my-deb-s3/dists/my-deb-s3/Release': Optional[110]
artipie  | [WARN] 2024-02-11 16:38:18,070 aws-java-sdk-NettyEventLoop-1-11 software.amazon.awssdk.http.nio.netty.internal.ResponseHandler - [Channel: 29ed635e] Subscriber cancelled before all events were published
artipie  | Feb 11, 2024 4:38:18 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Save 'my-deb-s3/dists/my-deb-s3/InRelease': Optional[110]
artipie  | Feb 11, 2024 4:38:19 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Save 'my-deb-s3/main/my-package.deb': Optional.empty
artipie  | Feb 11, 2024 4:38:19 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Value 'my-deb-s3/main/my-package': Optional[0]
artipie  | Feb 11, 2024 4:38:19 PM com.artipie.asto.LoggingStorage log
artipie  | INFO: Delete 'my-deb-s3/main/my-package'
artipie  | [INFO] 2024-02-11 16:38:19,574 sdk-async-response-0-25 com.artipie.http.MainSlice - << INTERNAL_ERROR```

**Comment by ChGen** [comment]
@Tzahif , thanks, what is your minIO version and configuration?

**Comment by ChGen** [comment]
@Tzahif , what command / deb file do you use currently for upload test / bug reproduction? Is it a single upload, or some batch processing?

**Comment by Tzahif** [comment]
@ChGen this is the command
```curl -i  -X PUT  --data-binary "@my-package.deb" http://0.0.0.0:8080/my-deb-s3/main/my-package.deb```
single upload and not batch

**Comment by ChGen** [comment]
@Tzahif , I've done local manual test with Artipie + minIO S3, using your `docker-compose.yaml` and configs above. I used `artipie/artipie-ubuntu:1.0-SNAPSHOT` built locally.
The only extra step required was bucket configuration:
```
mc alias set s3test http://localhost:9000 minio123 minio123
mc mb s3test/repo-test --region us-east-1
mc anonymous set public s3test/repo-test
# list:
mc ls -r s3test/repo-test
curl -f -kv http://localhost:9000/repo-test/
```

I used 3 deb files (see log) and also checked that those could be downloaded again and match originals.

```
ls -lah *.deb
-rw-r--r-- 1 evgeny evgeny  30K Nov 24 17:07 aglfn_1.7-3_amd64.deb
-rw-r--r-- 1 evgeny evgeny 1.3M Feb 14 10:06 libobus-ocaml_1.2.3-1+b3_amd64.deb
-rw-r--r-- 1 evgeny evgeny 3.7M Feb 14 09:55 pspp_1.2.0-3_amd64.deb

curl http://localhost:8080/my-deb-s3/main/aglfn.deb --upload-file aglfn_1.7-3_amd64.deb
curl -f -v http://localhost:8080/my-deb-s3/main/aglfn.deb -o aglfn-out.deb
cmp out.deb aglfn_1.7-3_amd64.deb

curl -i  -X PUT  --data-binary @pspp_1.2.0-3_amd64.deb http://localhost:8080/my-deb-s3/main/pspp.deb
curl -f -v http://localhost:8080/my-deb-s3/main/pspp.deb -o pspp-out.deb
cmp pspp* ; echo $?
0

curl -i  -X PUT  --data-binary @libobus-ocaml_1.2.3-1+b3_amd64.deb http://localhost:8080/my-deb-s3/main/libobus-ocaml.deb
curl -f -v http://localhost:8080/my-deb-s3/main/libobus-ocaml.deb -o libobus-ocaml-out.deb
cmp libobus-ocaml* ; echo $?
0

mc ls -r s3test/repo-test
[2024-02-14 10:10:03 MSK]   309B STANDARD my-deb-s3/dists/my-deb-s3/InRelease
[2024-02-14 10:10:03 MSK]   309B STANDARD my-deb-s3/dists/my-deb-s3/Release
[2024-02-14 10:10:03 MSK] 1.7KiB STANDARD my-deb-s3/dists/my-deb-s3/main/binary-amd64/Packages.gz
[2024-02-14 10:07:48 MSK]  29KiB STANDARD my-deb-s3/main/aglfn.deb
[2024-02-14 10:10:02 MSK] 1.3MiB STANDARD my-deb-s3/main/libobus-ocaml.deb
[2024-02-14 10:08:10 MSK] 3.6MiB STANDARD my-deb-s3/main/pspp.deb

curl -f -v http://localhost:8080/my-deb-s3/dists/my-deb-s3/main/binary-amd64/Packages.gz -o Packages-out.gz
cat Packages-out.gz |gzip -d|grep Package
Package: aglfn
Package: pspp
Package: libobus-ocaml

```

So, I was able to upload & download files without issues.

**Comment by ChGen** [comment]
@Tzahif , 
Do you have uploading/downloading errors with minIO S3 or `curl` freezes?
Do you have any files on S3 after uploads?
How do you configure your minIO S3 bucket?

**Comment by Tzahif** [comment]
@ChGen,
i am using the ubuntu dockerfile in the artipie-main directory.
i configured my minio bucket again like you wrote:
```
mc alias set s3test http://localhost:9000 minio123 minio123
mc mb s3test/repo-test --region us-east-1
mc anonymous set public s3test/repo-test
```

i was able to upload `aglfn_1.7-3_amd64.deb`.
i am using minio deb package from here - https://min.io/docs/minio/linux/index.html
```
wget https://dl.min.io/server/minio/release/linux-amd64/archive/minio_20240209212516.0.0_amd64.deb -O minio.deb

~ curl -i  -X PUT  --data-binary "@minio.deb" http://0.0.0.0:8080/my-deb-s3/main/minio.deb
HTTP/1.1 100 Continue

HTTP/1.1 500 Internal Server Error
transfer-encoding: chunked
```
logs from artipie container:
```
artipie  | [INFO] 2024-02-14 10:06:28,352 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - >> PUT /my-deb-s3/main/minio.deb HTTP_1_1
artipie  |
artipie  | Host: 0.0.0.0:8080
artipie  | User-Agent: curl/8.1.2
artipie  | Accept: */*
artipie  | Content-Length: 35721224
artipie  | Content-Type: application/x-www-form-urlencoded
artipie  | Expect: 100-continue
artipie  | [INFO] 2024-02-14 10:06:28,354 vert.x-eventloop-thread-0 com.artipie.http.MainSlice - << CONTINUE
artipie  | Feb 14, 2024 10:06:28 AM com.artipie.asto.LoggingStorage log
artipie  | INFO: Exists 'my-deb-s3/dists/my-deb-s3/Release': true
artipie  | Feb 14, 2024 10:06:29 AM com.artipie.asto.LoggingStorage log
artipie  | INFO: Save 'my-deb-s3/main/minio.deb': Optional.empty
artipie  | Feb 14, 2024 10:06:29 AM com.artipie.asto.LoggingStorage log
artipie  | INFO: Value 'my-deb-s3/main/minio.deb': Optional[0]
artipie  | Feb 14, 2024 10:06:29 AM com.artipie.asto.LoggingStorage log
artipie  | INFO: Delete 'my-deb-s3/main/minio.deb'
artipie  | [INFO] 2024-02-14 10:06:29,949 sdk-async-response-0-40 com.artipie.http.MainSlice - << INTERNAL_ERROR
```

files after uploading aglfn and trying to upload minio
<img width="382" alt="image" src="https://github.com/artipie/artipie/assets/3883674/9b33a451-d119-4ab1-b1a1-1de2618304be">

tell me if you can reproduce this error with minio.deb

**Comment by ChGen** [comment]
@Tzahif , I tested `minio.deb` and it is perfectly reproducible. The problem is due to relatively big `.deb` file size (multipart processing probably). I'll investigate it further and fix.
Meanwhile, could you check that small `.deb` files could be uploaded in your minIO and AWS S3 testing environment?
You can use our test files, for example: https://github.com/artipie/artipie/tree/master/debian-adapter/src/test/resources

**Comment by Tzahif** [comment]
@ChGen i tested small deb files on AWS S3, and it's working

**Comment by ChGen** [comment]
Should be fixed in master.
