### ISSUE TITLE
Allow insecure SSL certificates

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#213]
Add configuration option to allow insecure connection for unknown certificates. It should be **disabled by default**.

**Comment by g4s8** [comment]
@rultor release, tag=`0.6.9`

**Comment by 0crat** [comment]
The job [#213](https://github.com/artipie/artipie/issues/213) assigned to @g4s8[/z](https://www.0crat.com/u/g4s8), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/49ec8d39-a85d-4e27-bd40-d8f3a02cfc0d); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by g4s8** [comment]
Done

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#787](https://github.com/artipie/artipie/issues/787) is still not solved.

**Comment by 0pdd** [comment]
@g4s8 the only puzzle [#787](https://github.com/artipie/artipie/issues/787) is solved here.
