### ISSUE TITLE
Use Github tokens for central.artipie.com users

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#285]
Use GitHub personal tokens as HTTP basic authentication for central users, user generates token in personal settings, uses it as password for authentication and uses special username like `github.com/username`. Artipie authenticates user via GitHub API by token and validates username.

**Comment by Sammers21** [comment]
0 references to the official documentation. I suggest you add them

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#337](https://github.com/artipie/artipie/issues/337), [#339](https://github.com/artipie/artipie/issues/339) are still not solved.

**Comment by g4s8** [comment]
Done

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#337](https://github.com/artipie/artipie/issues/337) is still not solved; solved: [#339](https://github.com/artipie/artipie/issues/339).
