### ISSUE TITLE
Publish traffic and size metrics and publish to the dashboard.

### ISSUE THREAD

**Issue by g4s8** [artipie/artipie#425]
Collect metrics for traffic (upload and download) and repository sizes, and show these metrics on the dashboard.

**Comment by 0pdd** [comment]
@g4s8 2 puzzles [#446](https://github.com/artipie/artipie/issues/446), [#447](https://github.com/artipie/artipie/issues/447) are still not solved.

**Comment by g4s8** [comment]
Done in #439

**Comment by 0pdd** [comment]
@g4s8 the puzzle [#446](https://github.com/artipie/artipie/issues/446) is still not solved; solved: [#447](https://github.com/artipie/artipie/issues/447).
